// ISO 32000 predefined names
const isoPredefNames = {
    author: '/Author',
    basefont: '/BaseFont',
    contents: '/Contents',
    catalog: '/Catalog',
    count: '/Count',
    creationdate: '/CreationDate',
    creator: '/Creator',
    font: '/Font',
    info: '/Info',
    helvetica: '/Helvetica',
    keywords: '/Keywords',
    kids: '/Kids',
    length: '/Length',
    mediabox: '/MediaBox',
    moddate: '/ModDate',
    page: '/Page',
    pages: '/Pages',
    parent: '/Parent',
    producer: '/Producer',
    resources: '/Resources',
    root: '/Root',
    size: '/Size',
    subject: '/Subject',
    title: '/Title',
    type: '/Type',
    type1: '/Type1',
    subtype: '/Subtype',
}

module.exports = isoPredefNames